version = 1

[[annotations]]
path = ".github/renovate.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ruhani Rabin (Rabin)"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".github/workflows/mapping.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ruhani Rabin (Rabin)"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "logs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ruhani Rabin (Rabin)"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".markdownlint.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Ruhani Rabin (Rabin)"
SPDX-License-Identifier = "GPL-3.0-or-later"
