# SPDX-FileCopyrightText: 2026 Ruhani Rabin (Rabin)
#
# SPDX-License-Identifier: GPL-3.0-or-later
all:
  children:
    inventory_linux:
      children:
        homelab:
        vps:
        proxmox_shells:
    unattended_upgrades_linux:
      children:
        homelab:
        vps:
    maintenance_linux:
      children:
        homelab:
        vps:
    homelab:
      vars:
        ansible_user: root
      hosts:
        glow-941: { ansible_host: 10.1.71.13 }
        frost-278: { ansible_host: 10.1.71.12 }
        xenon-935: { ansible_host: 10.1.71.5 }
        rift-760: { ansible_host: 10.1.68.141 }
        mesh-143: { ansible_host: 10.1.68.112 }
        veil-945: { ansible_host: 10.1.68.62 }
        wave-956: { ansible_host: 10.1.71.3 }
        quartz-299: { ansible_host: 10.1.68.93 }
        glow-870: { ansible_host: 10.1.71.31 }
        flux-430: { ansible_host: 10.1.71.8 }
        veil-117: { ansible_host: 10.1.71.32 }
        atlas-715: { ansible_host: 10.1.71.9 }
        flux-708: { ansible_host: 10.1.71.4 }
        dune-679: { ansible_host: 10.1.71.14 }
        frost-996: { ansible_host: 10.1.71.7 }
        # debian 13 minipc nuc
        debian-nuc:
          ansible_host: 10.1.68.92
          unattended_upgrades_reboot_time: "05:00"
        # Example: custom reboot time for unattended-upgrades
        # example-custom-reboot: { ansible_host: 10.1.71.100, unattended_upgrades_reboot_time: "04:00" }
        quartz-782:
          ansible_host: 10.1.68.80
          unattended_upgrades_reboot_time: "10:00"
          unattended_upgrades_blacklist:
            - "nvidia-driver-535"
            - "nvidia-dkms-535"
            - "libnvidia-*"
    vps:
      vars:
        ansible_user: root
      hosts:
        # this instance is removed bolt-602: { ansible_host: 104.212.224.179 }
        spark-493: { ansible_host: 104.212.224.46 }
        sage-606: { ansible_host: 104.250.122.142 }
    proxmox_shells:
      vars:
        ansible_user: root
      hosts:
        proxmox-node01:
          ansible_host: 10.1.71.1
        proxmox-node02:
          ansible_host: 10.1.71.2
