# SPDX-FileCopyrightText: 2026 Ruhani Rabin (Rabin)
#
# SPDX-License-Identifier: GPL-3.0-or-later
all:
  children:
    homelab:
      vars:
        ansible_user: root
      hosts:
        glow-941: { ansible_host: 10.1.68.99 }
        xenon-935: { ansible_host: 10.1.71.5 }
        core-263: { ansible_host: 10.1.68.141 }
        mesh-143: { ansible_host: 10.1.68.112 }
        veil-945: { ansible_host: 10.1.68.62 }
        wave-956: { ansible_host: 10.1.71.3 }
        quartz-299: { ansible_host: 10.1.68.93 }
        veil-693: { ansible_host: 10.1.71.6 }
        glow-870: { ansible_host: 10.1.71.31 }
        flux-430: { ansible_host: 10.1.71.8 }
        veil-117: { ansible_host: 10.1.71.32 }
        torr-440: { ansible_host: 10.1.71.9 }
        # debian 13 minipc nuc
        debian-nuc:
          ansible_host: 10.1.68.92
          unattended_upgrades_reboot_time: "05:00"
        # Example: custom reboot time for unattended-upgrades
        # example-custom-reboot: { ansible_host: 10.1.71.100, unattended_upgrades_reboot_time: "04:00" }
        crest-217:
          ansible_host: 10.1.68.80
          unattended_upgrades_reboot_time: "10:00"
          unattended_upgrades_blacklist:
            - "nvidia-driver-535"
            - "nvidia-dkms-535"
            - "libnvidia-*"
    vps:
      vars:
        ansible_user: root
      hosts:
        bolt-602: { ansible_host: 104.212.224.179 }
        spark-493: { ansible_host: 104.212.224.46 }
