# SPDX-FileCopyrightText: 2026 Ruhani Rabin (Rabin)
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  role_name: semaphore
  author: Ruhani Rabin
  description: Install and configure Semaphore UI for Ansible
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble
        - jammy
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
