# SPDX-FileCopyrightText: 2026 Ruhani Rabin (Rabin)
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install shared SSH authorized keys across homelab nodes
  hosts: homelab:!debian-nuc
  become: true
  roles:
    - ssh_authorized_keys
